from datetime import datetime
import os


def generate_report(folder_path, stats):

    if not folder_path:
        raise Exception("No folder selected.")

    total_files = sum(stats.values())

    current_time = datetime.now()

    report_name = "organization_report.txt"

    report_path = os.path.join(folder_path, report_name)

    with open(report_path, "w", encoding="utf-8") as file:

        file.write("=" * 50 + "\n")
        file.write("        SMART FILE ORGANIZER REPORT\n")
        file.write("=" * 50 + "\n\n")

        file.write(f"Date : {current_time.strftime('%d-%m-%Y')}\n")
        file.write(f"Time : {current_time.strftime('%I:%M:%S %p')}\n\n")

        file.write(f"Folder : {folder_path}\n\n")

        file.write("-" * 50 + "\n")

        for category, count in stats.items():
            file.write(f"{category:<15}: {count}\n")

        file.write("-" * 50 + "\n\n")

        file.write(f"Total Files Organized : {total_files}\n\n")

        file.write("Generated by Smart File Organizer\n")
        file.write("=" * 50)

    return report_path